#pragma once

#ifndef DEBUG
#define DEBUG 0
#endif

// pins
#define PDA_ADXL345_SDA_PIN 0
#define PDA_ADXL345_SCL_PIN 1
#define PDA_STATUS_LED_PIN 13
#define PDA_BUZZER_PIN 14
#define PDA_ACTION_BUTTON_PIN 12
#define PDA_VOLTMETER_ADC_PIN 28
#define PDA_VOLTMETER_ADC_ID 2

// button actions
#define CLICK_DEBOUNCE_TIME 300

#define MIN_TIME_BETWEEN_CLICKS_FOR_ACTION 1200
#define CONTINOUS_CLICKS_TO_DISABLE_ALARM 5

// battery stats
#define BATTER_VOLTAGE_READINGS 30
#define MIN_BATTERY_VOLTAGE 3.3
