#pragma once

// pins
#define PDA_STATUS_LED_PIN 13
#define PDA_BUZZER_PIN 14
#define PDA_ACTION_BUTTON_PIN 12

// button actions
#define CLICK_DEBOUNCE_TIME 300

#define MIN_TIME_BETWEEN_CLICKS_FOR_ACTION 1200
#define CONTINOUS_CLICKS_TO_DISABLE_ALARM 5
